name: repairman
description: repairman semen
version: 1.5.6+29

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: any
  pub_semver: any
  flutter_user_agent: any
  cached_network_image: any
  sqflite: any
  dio: any
  image_picker: any
  intl: any
  cupertino_icons: any
  url_launcher: any
  location: any
  great_circle_distance:
    git:
      url: git://github.com/swipesight/great_circle_distance.dart
  barcode_scan: any
  firebase_messaging: any
  sentry_flutter: any
  flutter_dotenv: any
  shared_preferences: any
  package_info: any
  yandex_mapkit: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/data/schema.sql
    - .env
    - lib/app/assets/images/beelineicon.jpg
    - lib/app/assets/images/megafonicon.jpg
    - lib/app/assets/images/mtsicon.png
    - lib/app/assets/images/tele2icon.jpeg
    - lib/app/assets/images/unknownicon.png
    - lib/app/assets/images/usericon.png
    - lib/app/assets/images/placeicon.png
    - lib/app/assets/images/placedoneicon.png
    - lib/app/assets/images/placenotdoneicon.png
    - lib/app/assets/images/placeinc.png

  uses-material-design: true
