name: repairman
description: repairman semen
version: 1.2.8+1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: any
  sqflite: any
  http: any
  intl: any
  cupertino_icons: any
  url_launcher: any
  location: any
  great_circle_distance:
    git:
      url: git://github.com/swipesight/great_circle_distance.dart
  barcode_scan: any
  firebase_messaging: any
  sentry: any
  dotenv: any
  shared_preferences: any
  device_info: any
  package_info: any
  yandex_mapkit:
    git:
      url: git://github.com/Unact/yandex_mapkit

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/data/schema.sql
    - .app_env
    - lib/app/assets/images/beelineicon.jpg
    - lib/app/assets/images/megafonicon.jpg
    - lib/app/assets/images/mtsicon.png
    - lib/app/assets/images/tele2icon.jpeg
    - lib/app/assets/images/unknownicon.png
    - lib/app/assets/images/usericon.png
    - lib/app/assets/images/placeicon.png

  uses-material-design: true
